### ISSUE TITLE
When loading the contexts, an exception is raised

### ISSUE THREAD

**Issue by KowalskiThomas** [DrBomb/python-steamcommunity#2]
It works the same on two accounts, I get the following error.

![error](https://cloud.githubusercontent.com/assets/14239160/17462791/e4fca91e-5c85-11e6-9705-844eec114202.PNG)

The lines concerned seem to be

```
try:

    self.MyContexts = json.loads(re.search(r"var g_rgAppContextData = ([\s\"\\\/\-\w\d\{\}\[\]\:\.\,\']+);",text).group(1))

    self.PartnerContexts = json.loads(re.search(r"var g_rgPartnerAppContextData = ([\s\"\\\/\-\w\d\{\}\[\]\:\.\,\']+);",text).group(1))

    self.PartnerSteamID = long(re.search(r"UserThem\.SetSteamId\( \'(\d+)\' \);",text).group(1))

    self.OurEscrow = int(re.search(r"var g_daysMyEscrow = (\d+);",text).group(1))

    self.TheirEscrow = int(re.search(r"var g_daysTheirEscrow = (\d+);",text).group(1))

except:

    print tradeURLResponse.text 

    raise
```

**Comment by DrBomb** [comment]
Could you give me the userID, app and context of this user? to check which context it has

**Comment by KowalskiThomas** [comment]
I'm sorry everything is my fault it was a faulty parameter.

**Comment by KowalskiThomas** [comment]
Well I reopen it since it happens again.

The App is 753, the context is 6 and the userID is Swappy (76561198107889055) (trade URL : https://steamcommunity.com/tradeoffer/new/?partner=147623327&token=jNOS2Euh)

**Comment by DrBomb** [comment]
Context guessing is based on a regular expression that catches the json string coded into the website response. This is quite error prone because I must tell the selector which characters are being expected on the json string.

I might have to change that in the future but for now It'll have to stay this way.

I've now pushed a fix for your case, alongside a better exception handler for error messages from valve
